export const GET_ACCESSORIES_START = "GET_ACCESSORIES_START";
export const GET_ACCESSORIES_SUCCESS = "GET_ACCESSORIES_SUCCESS";
export const GET_ACCESSORIES_FAIL = "GET_ACCESSORIES_FAIL";

export const CREATE_ACCESSORY_START = "CREATE_ACCESSORY_START";
export const CREATE_ACCESSORY_SUCCESS = "CREATE_ACCESSORY_SUCCESS";
export const CREATE_ACCESSORY_FAIL = "CREATE_ACCESSORY_FAIL";
