export const GET_ITEMS_START = "GET_ITEMS_START";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAIL = "GET_ITEMS_FAIL";

export const CREATE_ITEM_START = "CREATE_ITEM_START";
export const CREATE_ITEM_SUCCESS = "CREATE_ITEM_SUCCESS";
export const CREATE_ITEM_FAIL = "CREATE_ITEM_FAIL";
