export const GET_SPECIFICATIONS_START = "GET_SPECIFICATIONS_START";
export const GET_SPECIFICATIONS_SUCCESS = "GET_SPECIFICATIONS_SUCCESS";
export const GET_SPECIFICATIONS_FAIL = "GET_SPECIFICATIONS_FAIL";

export const CREATE_SPECIFICATION_START = "CREATE_SPECIFICATION_START";
export const CREATE_SPECIFICATION_SUCCESS = "CREATE_SPECIFICATION_SUCCESS";
export const CREATE_SPECIFICATION_FAIL = "CREATE_SPECIFICATION_FAIL";
